name: ssg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - h5py=3.6.0
  - numpy=1.22.3
  - pillow=9.0.1
  - pip=21.2.4
  - python=3.10.4
  - pytorch=1.11.0
  - scikit-image=0.19.2
  - scipy=1.7.3
  - tensorboardx=2.2
  - tqdm=4.64.0
  - pip:
    - pymcubes==0.1.2
    - trimesh==3.12.5
    - pyglet==1.5.26
    - open3d==0.15.1
